spring.application.name=smartcampus

# Use a non-default port to avoid conflicts
server.port=8086

# MongoDB Connection Configuration
# If you are using a local MongoDB installation (like MongoDB Compass):
# spring.data.mongodb.uri=mongodb://localhost:27017/campus_nexus

# IMPORTANT: If you are using MongoDB Atlas (the cloud version), comment out the line above
# and paste your Atlas connection string below instead (include a database name):
spring.data.mongodb.uri=mongodb+srv://nethna2001:okH17JljL9PwAygb@paf.9pqijns.mongodb.net/campus_nexus?appName=PAF

